server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
      routes:
        - id: loan
          uri: lb://loan/
          predicates:
            - Path=/api/loans/**
        - id: status
          uri: lb://status/
          predicates:
            - Path=/api/status/**
        - id: loan-type
          uri: lb://loan-type
          predicates:
            - Path=/api/loan-type/**
        - id: mainframe
          uri: lb://mainframe
          predicates:
            - Path=/api/mainframe/**
