server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pb-status
    username: postgres
    password: root
  eureka:
    instance:
      preferIpAddress: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
