pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/torokokoo/prestabanco']])
                dir("front"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("front"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            sh "docker buildx create --use"
                            sh "docker buildx build --platform linux/amd64 -t torokoko/prestabanco-frontend:prod ."
                            sh "docker push torokoko/prestabanco-frontend:prod"
                        }
                    }                    
                }
            }
        }
    }
}