pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/torokokoo/prestabanco']])
                dir("api"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("api"){
                    sh "mvn test"
                }
            }
        }        
        stage("Build and Push Docker Image"){
            steps{
                dir("api"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            sh "docker buildx build --platform linux/amd64 -t torokoko/prestabanco-backend:prod ."
                            sh "docker push torokoko/prestabanco-backend:prod"
                        }
                    }                    
                }
            }
        }
    }
}